### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by xNabil** [akasakaid/NotPixTod#7]
Hello,
recently I am having this error
please fix this🫂🥺

`[20:24:58]-[acc 8] login as nk (19) (huzur)
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/NotPixTod/bot.py", line 466, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/NotPixTod/bot.py", line 440, in main
    result = await asyncio.gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/NotPixTod/bot.py", line 341, in bound
    return await NotPixTod(*data).start(phone)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/NotPixTod/bot.py", line 265, in start
    query = await self.telegram_login(phone=phone, proxy=proxy, return_data=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/NotPixTod/bot.py", line 236, in telegram_login
    bot_id=await client.get_input_entity(peer=bot_username),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/users.py", line 440, in get_input_entity
    await self._get_entity_from_string(peer))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/users.py", line 556, in _get_entity_from_string
    result = await self(
             ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 86 seconds is required (caused by ResolveUsernameRequest)
~/NotPixTod $`
![Uploading Screenshot_20241007-202515.jpg…]()

**Comment by akasakaid** [comment]
The error has been handled.

**Comment by xNabil** [comment]
> The error has been handled.

do i have to do anything? like update or anything?
i cloned the repo using termux 3 days ago

and thanks brother 🫂💝 your repo is great

**Comment by akasakaid** [comment]
You need to update it.

**Comment by xNabil** [comment]
yeah, updated it using `git pull`

thanks brother, really like your works
